package com.alexhulbert.jmobiledevice.diagnostics;

import static com.alexhulbert.jmobiledevice.diagnostics.Counter.i;

public enum Keys {
    DieId,
    SerialNumber,
    UniqueChipID,
    WifiAddress,
    CPUArchitecture,
    BluetoothAddress,
    EthernetMacAddress,
    FirmwareVersion,
    MLBSerialNumber,
    ModelNumber,
    RegionInfo,
    RegionCode,
    DeviceClass,
    ProductType,
    DeviceName,
    UserAssignedDeviceName,
    HWModelStr,
    SigningFuse,
    SoftwareBehavior,
    SupportedKeyboards,
    BuildVersion,
    ProductVersion,
    ReleaseType,
    InternalBuild,
    CarrierInstallCapability,
    IsUIBuild,
    InternationalMobileEquipmentIdentity,
    MobileEquipmentIdentifier,
    DeviceColor,
    HasBaseband,
    SupportedDeviceFamilies,
    SoftwareBundleVersion,
    SDIOManufacturerTuple,
    SDIOProductInfo,
    UniqueDeviceID,
    InverseDeviceID,
    ChipID,
    PartitionType,
    ProximitySensorCalibration,
    CompassCalibration,
    WirelessBoardSnum,
    BasebandBoardSnum,
    HardwarePlatform,
    RequiredBatteryLevelForSoftwareUpdate,
    IsThereEnoughBatteryLevelForSoftwareUpdate,
    BasebandRegionSKU,
    encrypted_data_partition,
    SysCfg,
    DiagData,
    SIMTrayStatus,
    CarrierBundleInfoArray,
    AllDeviceCapabilities,
    wi_fi,
    SBAllowSensitiveUI,
    green_tea,
    not_green_tea,
    AllowYouTube,
    AllowYouTubePlugin,
    SBCanForceDebuggingInfo,
    AppleInternalInstallCapability,
    HasAllFeaturesCapability,
    ScreenDimensions,
    IsSimulator,
    BasebandSerialNumber,
    BasebandChipId,
    BasebandCertId,
    BasebandSkeyId,
    BasebandFirmwareVersion,
    cellular_data,
    contains_cellular_radio,
    RegionalBehaviorGoogleMail,
    RegionalBehaviorVolumeLimit,
    RegionalBehaviorShutterClick,
    RegionalBehaviorNTSC,
    RegionalBehaviorNoWiFi,
    RegionalBehaviorChinaBrick,
    RegionalBehaviorNoVOIP,
    RegionalBehaviorAll,
    ApNonce;
    
    public double value;
    private Keys() {
        value = Math.pow(2, i);
        i++;
    }
}
